const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
$$('[data-year]').forEach(n=>n.textContent=new Date().getFullYear());
const menu=$('.menu-toggle'),nav=$('#site-nav');
if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});$$('a',nav).forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open');document.body.classList.remove('menu-open')}))}
const header=$('[data-header]'),updateHeader=()=>header?.classList.toggle('scrolled',scrollY>24);updateHeader();addEventListener('scroll',updateHeader,{passive:true});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e))}else $$('.reveal').forEach(e=>e.classList.add('visible'));
const labels={fabric:'포신한 직물의 감촉',organize:'정갈한 일상의 여백',outdoor:'든든한 밖의 시간'};
const card=(p,featured=false)=>`<article class="product-card ${featured?'featured':''} reveal visible"><a class="product-visual ${p.category}" href="${p.url}" target="_blank" rel="noopener" aria-label="${p.name} 쿠팡에서 보기">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:`<span>${labels[p.category]||'일상을 위한 물건'}</span>`}<em>${p.categoryLabel}</em></a><div class="product-info"><p>${p.categoryLabel}</p><h3>${p.name}</h3><span>${p.tagline}</span><div class="product-actions"><a class="text-link" href="${p.url}" target="_blank" rel="noopener">쿠팡에서 가격 보기 <span aria-hidden="true">↗</span></a><button type="button" class="cart-add" data-cart-add data-name="${p.name}" data-price="0" data-url="${p.url}">담기</button></div></div></article>`;
async function products(){const cs=$$('[data-product-list]');if(!cs.length)return;try{const r=await fetch('products.json');if(!r.ok)throw 0;const d=await r.json();cs.forEach(c=>{const list=c.dataset.category?d.products.filter(p=>p.category===c.dataset.category):d.products;c.innerHTML=list.slice(0,Number(c.dataset.limit||list.length)).map((p,i)=>card(p,i===0&&!c.dataset.category)).join('')})}catch{cs.forEach(c=>c.innerHTML='<p class="empty-note">제품을 준비하고 있어요.</p>')}}
async function stories(){const cs=$$('[data-story-list]');if(!cs.length)return;try{const r=await fetch('story/posts.json');if(!r.ok)throw 0;const d=await r.json();cs.forEach(c=>c.innerHTML=d.slice(0,Number(c.dataset.limit||d.length)).map(p=>`<article class="story-card reveal visible"><p>${p.tags?.[0]||'LIVING NOTE'} · ${p.date}</p><h3><a href="story/${p.url||`post.html?id=${p.id}`}">${p.title}</a></h3><span>${p.summary}</span><a class="text-link" href="story/${p.url||`post.html?id=${p.id}`}">읽어보기 <span aria-hidden="true">→</span></a></article>`).join(''))}catch{cs.forEach(c=>c.innerHTML='<p class="empty-note">생활 이야기를 준비하고 있어요.</p>')}}
products();stories();
